package cz.jurca.fieldreservationsystem.domain

data class Address(val city: City, val street: Street, val zipCode: ZipCode, val country: Country)

@JvmInline
value class City(val value: String) {
    init {
        require(value.isNotBlank()) { "City cannot be blank" }
    }
}

@JvmInline
value class Street(val value: String) {
    init {
        require(value.isNotBlank()) { "Street cannot be blank" }
    }
}

@JvmInline
value class ZipCode(val value: String) {
    init {
        require(value.isNotBlank()) { "Zip code cannot be blank" }
    }
}

enum class Country(val countryName: Name, val alphaCode3: AlphaCode3) {
    AFGHANISTAN(Name("Afghanistan"), AlphaCode3("AFG")),
    ALBANIA(Name("Albania"), AlphaCode3("ALB")),
    ALGERIA(Name("Algeria"), AlphaCode3("DZA")),
    AMERICAN_SAMOA(Name("American Samoa"), AlphaCode3("ASM")),
    ANDORRA(Name("Andorra"), AlphaCode3("AND")),
    ANGOLA(Name("Angola"), AlphaCode3("AGO")),
    ANGUILLA(Name("Anguilla"), AlphaCode3("AIA")),
    ANTARCTICA(Name("Antarctica"), AlphaCode3("ATA")),
    ANTIGUA_AND_BARBUDA(Name("Antigua and Barbuda"), AlphaCode3("ATG")),
    ARGENTINA(Name("Argentina"), AlphaCode3("ARG")),
    ARMENIA(Name("Armenia"), AlphaCode3("ARM")),
    ARUBA(Name("Aruba"), AlphaCode3("ABW")),
    AUSTRALIA(Name("Australia"), AlphaCode3("AUS")),
    AUSTRIA(Name("Austria"), AlphaCode3("AUT")),
    AZERBAIJAN(Name("Azerbaijan"), AlphaCode3("AZE")),
    BAHAMAS(Name("Bahamas (the)"), AlphaCode3("BHS")),
    BAHRAIN(Name("Bahrain"), AlphaCode3("BHR")),
    BANGLADESH(Name("Bangladesh"), AlphaCode3("BGD")),
    BARBADOS(Name("Barbados"), AlphaCode3("BRB")),
    BELARUS(Name("Belarus"), AlphaCode3("BLR")),
    BELGIUM(Name("Belgium"), AlphaCode3("BEL")),
    BELIZE(Name("Belize"), AlphaCode3("BLZ")),
    BENIN(Name("Benin"), AlphaCode3("BEN")),
    BERMUDA(Name("Bermuda"), AlphaCode3("BMU")),
    BHUTAN(Name("Bhutan"), AlphaCode3("BTN")),
    BOLIVIA(Name("Bolivia (Plurinational State of)"), AlphaCode3("BOL")),
    BONAIRE_SINT_EUSTATIUS_AND_SABA(Name("Bonaire, Sint Eustatius and Saba"), AlphaCode3("BES")),
    BOSNIA_AND_HERZEGOVINA(Name("Bosnia and Herzegovina"), AlphaCode3("BIH")),
    BOTSWANA(Name("Botswana"), AlphaCode3("BWA")),
    BOUVET_ISLAND(Name("Bouvet Island"), AlphaCode3("BVT")),
    BRAZIL(Name("Brazil"), AlphaCode3("BRA")),
    BRITISH_INDIAN_OCEAN_TERRITORY(Name("British Indian Ocean Territory (the)"), AlphaCode3("IOT")),
    BRUNEI_DARUSSALAM(Name("Brunei Darussalam"), AlphaCode3("BRN")),
    BULGARIA(Name("Bulgaria"), AlphaCode3("BGR")),
    BURKINA_FASO(Name("Burkina Faso"), AlphaCode3("BFA")),
    BURUNDI(Name("Burundi"), AlphaCode3("BDI")),
    CABO_VERDE(Name("Cabo Verde"), AlphaCode3("CPV")),
    CAMBODIA(Name("Cambodia"), AlphaCode3("KHM")),
    CAMEROON(Name("Cameroon"), AlphaCode3("CMR")),
    CANADA(Name("Canada"), AlphaCode3("CAN")),
    CAYMAN_ISLANDS(Name("Cayman Islands (the)"), AlphaCode3("CYM")),
    CENTRAL_AFRICAN_REPUBLIC(Name("Central African Republic (the)"), AlphaCode3("CAF")),
    CHAD(Name("Chad"), AlphaCode3("TCD")),
    CHILE(Name("Chile"), AlphaCode3("CHL")),
    CHINA(Name("China"), AlphaCode3("CHN")),
    CHRISTMAS_ISLAND(Name("Christmas Island"), AlphaCode3("CXR")),
    COCOS_KEELING_ISLANDS(Name("Cocos (Keeling) Islands (the)"), AlphaCode3("CCK")),
    COLOMBIA(Name("Colombia"), AlphaCode3("COL")),
    COMOROS(Name("Comoros (the)"), AlphaCode3("COM")),
    CONGO_DEMOCRATIC_REPUBLIC(Name("Congo (the Democratic Republic of the)"), AlphaCode3("COD")),
    CONGO(Name("Congo (the)"), AlphaCode3("COG")),
    COOK_ISLANDS(Name("Cook Islands (the)"), AlphaCode3("COK")),
    COSTA_RICA(Name("Costa Rica"), AlphaCode3("CRI")),
    CROATIA(Name("Croatia"), AlphaCode3("HRV")),
    CUBA(Name("Cuba"), AlphaCode3("CUB")),
    CURACAO(Name("Curaçao"), AlphaCode3("CUW")),
    CYPRUS(Name("Cyprus"), AlphaCode3("CYP")),
    CZECH_REPUBLIC(Name("Czechia"), AlphaCode3("CZE")),
    COTE_DIVOIRE(Name("Côte d'Ivoire"), AlphaCode3("CIV")),
    DENMARK(Name("Denmark"), AlphaCode3("DNK")),
    DJIBOUTI(Name("Djibouti"), AlphaCode3("DJI")),
    DOMINICA(Name("Dominica"), AlphaCode3("DMA")),
    DOMINICAN_REPUBLIC(Name("Dominican Republic (the)"), AlphaCode3("DOM")),
    ECUADOR(Name("Ecuador"), AlphaCode3("ECU")),
    EGYPT(Name("Egypt"), AlphaCode3("EGY")),
    EL_SALVADOR(Name("El Salvador"), AlphaCode3("SLV")),
    EQUATORIAL_GUINEA(Name("Equatorial Guinea"), AlphaCode3("GNQ")),
    ERITREA(Name("Eritrea"), AlphaCode3("ERI")),
    ESTONIA(Name("Estonia"), AlphaCode3("EST")),
    ESWATINI(Name("Eswatini"), AlphaCode3("SWZ")),
    ETHIOPIA(Name("Ethiopia"), AlphaCode3("ETH")),
    FALKLAND_ISLANDS(Name("Falkland Islands (the) [Malvinas]"), AlphaCode3("FLK")),
    FAROE_ISLANDS(Name("Faroe Islands (the)"), AlphaCode3("FRO")),
    FIJI(Name("Fiji"), AlphaCode3("FJI")),
    FINLAND(Name("Finland"), AlphaCode3("FIN")),
    FRANCE(Name("France"), AlphaCode3("FRA")),
    FRENCH_GUIANA(Name("French Guiana"), AlphaCode3("GUF")),
    FRENCH_POLYNESIA(Name("French Polynesia"), AlphaCode3("PYF")),
    FRENCH_SOUTHERN_TERRITORIES(Name("French Southern Territories (the)"), AlphaCode3("ATF")),
    GABON(Name("Gabon"), AlphaCode3("GAB")),
    GAMBIA(Name("Gambia (the)"), AlphaCode3("GMB")),
    GEORGIA(Name("Georgia"), AlphaCode3("GEO")),
    GERMANY(Name("Germany"), AlphaCode3("DEU")),
    GHANA(Name("Ghana"), AlphaCode3("GHA")),
    GIBRALTAR(Name("Gibraltar"), AlphaCode3("GIB")),
    GREECE(Name("Greece"), AlphaCode3("GRC")),
    GREENLAND(Name("Greenland"), AlphaCode3("GRL")),
    GRENADA(Name("Grenada"), AlphaCode3("GRD")),
    GUADELOUPE(Name("Guadeloupe"), AlphaCode3("GLP")),
    GUAM(Name("Guam"), AlphaCode3("GUM")),
    GUATEMALA(Name("Guatemala"), AlphaCode3("GTM")),
    GUERNSEY(Name("Guernsey"), AlphaCode3("GGY")),
    GUINEA(Name("Guinea"), AlphaCode3("GIN")),
    GUINEA_BISSAU(Name("Guinea-Bissau"), AlphaCode3("GNB")),
    GUYANA(Name("Guyana"), AlphaCode3("GUY")),
    HAITI(Name("Haiti"), AlphaCode3("HTI")),
    HEARD_ISLAND_AND_MCDONALD_ISLANDS(Name("Heard Island and McDonald Islands"), AlphaCode3("HMD")),
    HOLY_SEE(Name("Holy See (the)"), AlphaCode3("VAT")),
    HONDURAS(Name("Honduras"), AlphaCode3("HND")),
    HONG_KONG(Name("Hong Kong"), AlphaCode3("HKG")),
    HUNGARY(Name("Hungary"), AlphaCode3("HUN")),
    ICELAND(Name("Iceland"), AlphaCode3("ISL")),
    INDIA(Name("India"), AlphaCode3("IND")),
    INDONESIA(Name("Indonesia"), AlphaCode3("IDN")),
    IRAN(Name("Iran (Islamic Republic of)"), AlphaCode3("IRN")),
    IRAQ(Name("Iraq"), AlphaCode3("IRQ")),
    IRELAND(Name("Ireland"), AlphaCode3("IRL")),
    ISLE_OF_MAN(Name("Isle of Man"), AlphaCode3("IMN")),
    ISRAEL(Name("Israel"), AlphaCode3("ISR")),
    ITALY(Name("Italy"), AlphaCode3("ITA")),
    JAMAICA(Name("Jamaica"), AlphaCode3("JAM")),
    JAPAN(Name("Japan"), AlphaCode3("JPN")),
    JERSEY(Name("Jersey"), AlphaCode3("JEY")),
    JORDAN(Name("Jordan"), AlphaCode3("JOR")),
    KAZAKHSTAN(Name("Kazakhstan"), AlphaCode3("KAZ")),
    KENYA(Name("Kenya"), AlphaCode3("KEN")),
    KIRIBATI(Name("Kiribati"), AlphaCode3("KIR")),
    KOREA_DEMOCRATIC_PEOPLES_REPUBLIC(Name("Korea (the Democratic People's Republic of)"), AlphaCode3("PRK")),
    KOREA_REPUBLIC(Name("Korea (the Republic of)"), AlphaCode3("KOR")),
    KUWAIT(Name("Kuwait"), AlphaCode3("KWT")),
    KYRGYZSTAN(Name("Kyrgyzstan"), AlphaCode3("KGZ")),
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC(Name("Lao People's Democratic Republic (the)"), AlphaCode3("LAO")),
    LATVIA(Name("Latvia"), AlphaCode3("LVA")),
    LEBANON(Name("Lebanon"), AlphaCode3("LBN")),
    LESOTHO(Name("Lesotho"), AlphaCode3("LSO")),
    LIBERIA(Name("Liberia"), AlphaCode3("LBR")),
    LIBYA(Name("Libya"), AlphaCode3("LBY")),
    LIECHTENSTEIN(Name("Liechtenstein"), AlphaCode3("LIE")),
    LITHUANIA(Name("Lithuania"), AlphaCode3("LTU")),
    LUXEMBOURG(Name("Luxembourg"), AlphaCode3("LUX")),
    MACAO(Name("Macao"), AlphaCode3("MAC")),
    MADAGASCAR(Name("Madagascar"), AlphaCode3("MDG")),
    MALAWI(Name("Malawi"), AlphaCode3("MWI")),
    MALAYSIA(Name("Malaysia"), AlphaCode3("MYS")),
    MALDIVES(Name("Maldives"), AlphaCode3("MDV")),
    MALI(Name("Mali"), AlphaCode3("MLI")),
    MALTA(Name("Malta"), AlphaCode3("MLT")),
    MARSHALL_ISLANDS(Name("Marshall Islands (the)"), AlphaCode3("MHL")),
    MARTINIQUE(Name("Martinique"), AlphaCode3("MTQ")),
    MAURITANIA(Name("Mauritania"), AlphaCode3("MRT")),
    MAURITIUS(Name("Mauritius"), AlphaCode3("MUS")),
    MAYOTTE(Name("Mayotte"), AlphaCode3("MYT")),
    MEXICO(Name("Mexico"), AlphaCode3("MEX")),
    MICRONESIA(Name("Micronesia (Federated States of)"), AlphaCode3("FSM")),
    MOLDOVA(Name("Moldova (the Republic of)"), AlphaCode3("MDA")),
    MONACO(Name("Monaco"), AlphaCode3("MCO")),
    MONGOLIA(Name("Mongolia"), AlphaCode3("MNG")),
    MONTENEGRO(Name("Montenegro"), AlphaCode3("MNE")),
    MONTSERRAT(Name("Montserrat"), AlphaCode3("MSR")),
    MOROCCO(Name("Morocco"), AlphaCode3("MAR")),
    MOZAMBIQUE(Name("Mozambique"), AlphaCode3("MOZ")),
    MYANMAR(Name("Myanmar"), AlphaCode3("MMR")),
    NAMIBIA(Name("Namibia"), AlphaCode3("NAM")),
    NAURU(Name("Nauru"), AlphaCode3("NRU")),
    NEPAL(Name("Nepal"), AlphaCode3("NPL")),
    NETHERLANDS(Name("Netherlands (the)"), AlphaCode3("NLD")),
    NEW_CALEDONIA(Name("New Caledonia"), AlphaCode3("NCL")),
    NEW_ZEALAND(Name("New Zealand"), AlphaCode3("NZL")),
    NICARAGUA(Name("Nicaragua"), AlphaCode3("NIC")),
    NIGER(Name("Niger (the)"), AlphaCode3("NER")),
    NIGERIA(Name("Nigeria"), AlphaCode3("NGA")),
    NIUE(Name("Niue"), AlphaCode3("NIU")),
    NORFOLK_ISLAND(Name("Norfolk Island"), AlphaCode3("NFK")),
    NORTHERN_MARIANA_ISLANDS(Name("Northern Mariana Islands (the)"), AlphaCode3("MNP")),
    NORWAY(Name("Norway"), AlphaCode3("NOR")),
    OMAN(Name("Oman"), AlphaCode3("OMN")),
    PAKISTAN(Name("Pakistan"), AlphaCode3("PAK")),
    PALAU(Name("Palau"), AlphaCode3("PLW")),
    PALESTINE(Name("Palestine, State of"), AlphaCode3("PSE")),
    PANAMA(Name("Panama"), AlphaCode3("PAN")),
    PAPUA_NEW_GUINEA(Name("Papua New Guinea"), AlphaCode3("PNG")),
    PARAGUAY(Name("Paraguay"), AlphaCode3("PRY")),
    PERU(Name("Peru"), AlphaCode3("PER")),
    PHILIPPINES(Name("Philippines (the)"), AlphaCode3("PHL")),
    PITCAIRN(Name("Pitcairn"), AlphaCode3("PCN")),
    POLAND(Name("Poland"), AlphaCode3("POL")),
    PORTUGAL(Name("Portugal"), AlphaCode3("PRT")),
    PUERTO_RICO(Name("Puerto Rico"), AlphaCode3("PRI")),
    QATAR(Name("Qatar"), AlphaCode3("QAT")),
    REPUBLIC_OF_NORTH_MACEDONIA(Name("Republic of North Macedonia"), AlphaCode3("MKD")),
    ROMANIA(Name("Romania"), AlphaCode3("ROU")),
    RUSSIAN_FEDERATION(Name("Russian Federation (the)"), AlphaCode3("RUS")),
    RWANDA(Name("Rwanda"), AlphaCode3("RWA")),
    REUNION(Name("Réunion"), AlphaCode3("REU")),
    SAINT_BARTHELEMY(Name("Saint Barthélemy"), AlphaCode3("BLM")),
    SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA(Name("Saint Helena, Ascension and Tristan da Cunha"), AlphaCode3("SHN")),
    SAINT_KITTS_AND_NEVIS(Name("Saint Kitts and Nevis"), AlphaCode3("KNA")),
    SAINT_LUCIA(Name("Saint Lucia"), AlphaCode3("LCA")),
    SAINT_MARTIN_FRENCH_PART(Name("Saint Martin (French part)"), AlphaCode3("MAF")),
    SAINT_PIERRE_AND_MIQUELON(Name("Saint Pierre and Miquelon"), AlphaCode3("SPM")),
    SAINT_VINCENT_AND_THE_GRENADINES(Name("Saint Vincent and the Grenadines"), AlphaCode3("VCT")),
    SAMOA(Name("Samoa"), AlphaCode3("WSM")),
    SAN_MARINO(Name("San Marino"), AlphaCode3("SMR")),
    SAO_TOME_AND_PRINCIPE(Name("Sao Tome and Principe"), AlphaCode3("STP")),
    SAUDI_ARABIA(Name("Saudi Arabia"), AlphaCode3("SAU")),
    SENEGAL(Name("Senegal"), AlphaCode3("SEN")),
    SERBIA(Name("Serbia"), AlphaCode3("SRB")),
    SEYCHELLES(Name("Seychelles"), AlphaCode3("SYC")),
    SIERRA_LEONE(Name("Sierra Leone"), AlphaCode3("SLE")),
    SINGAPORE(Name("Singapore"), AlphaCode3("SGP")),
    SINT_MAARTEN_DUTCH_PART(Name("Sint Maarten (Dutch part)"), AlphaCode3("SXM")),
    SLOVAKIA(Name("Slovakia"), AlphaCode3("SVK")),
    SLOVENIA(Name("Slovenia"), AlphaCode3("SVN")),
    SOLOMON_ISLANDS(Name("Solomon Islands"), AlphaCode3("SLB")),
    SOMALIA(Name("Somalia"), AlphaCode3("SOM")),
    SOUTH_AFRICA(Name("South Africa"), AlphaCode3("ZAF")),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS(Name("South Georgia and the South Sandwich Islands"), AlphaCode3("SGS")),
    SOUTH_SUDAN(Name("South Sudan"), AlphaCode3("SSD")),
    SPAIN(Name("Spain"), AlphaCode3("ESP")),
    SRI_LANKA(Name("Sri Lanka"), AlphaCode3("LKA")),
    SUDAN(Name("Sudan (the)"), AlphaCode3("SDN")),
    SURINAME(Name("Suriname"), AlphaCode3("SUR")),
    SVALBARD_AND_JAN_MAYEN(Name("Svalbard and Jan Mayen"), AlphaCode3("SJM")),
    SWEDEN(Name("Sweden"), AlphaCode3("SWE")),
    SWITZERLAND(Name("Switzerland"), AlphaCode3("CHE")),
    SYRIAN_ARAB_REPUBLIC(Name("Syrian Arab Republic"), AlphaCode3("SYR")),
    TAIWAN(Name("Taiwan (Province of China)"), AlphaCode3("TWN")),
    TAJIKISTAN(Name("Tajikistan"), AlphaCode3("TJK")),
    TANZANIA(Name("Tanzania, United Republic of"), AlphaCode3("TZA")),
    THAILAND(Name("Thailand"), AlphaCode3("THA")),
    TIMOR_LESTE(Name("Timor-Leste"), AlphaCode3("TLS")),
    TOGO(Name("Togo"), AlphaCode3("TGO")),
    TOKELAU(Name("Tokelau"), AlphaCode3("TKL")),
    TONGA(Name("Tonga"), AlphaCode3("TON")),
    TRINIDAD_AND_TOBAGO(Name("Trinidad and Tobago"), AlphaCode3("TTO")),
    TUNISIA(Name("Tunisia"), AlphaCode3("TUN")),
    TURKEY(Name("Turkey"), AlphaCode3("TUR")),
    TURKMENISTAN(Name("Turkmenistan"), AlphaCode3("TKM")),
    TURKS_AND_CAICOS_ISLANDS(Name("Turks and Caicos Islands (the)"), AlphaCode3("TCA")),
    TUVALU(Name("Tuvalu"), AlphaCode3("TUV")),
    UGANDA(Name("Uganda"), AlphaCode3("UGA")),
    UKRAINE(Name("Ukraine"), AlphaCode3("UKR")),
    UNITED_ARAB_EMIRATES(Name("United Arab Emirates (the)"), AlphaCode3("ARE")),
    UNITED_KINGDOM(Name("United Kingdom of Great Britain and Northern Ireland (the)"), AlphaCode3("GBR")),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS(Name("United States Minor Outlying Islands (the)"), AlphaCode3("UMI")),
    UNITED_STATES_OF_AMERICA(Name("United States of America (the)"), AlphaCode3("USA")),
    URUGUAY(Name("Uruguay"), AlphaCode3("URY")),
    UZBEKISTAN(Name("Uzbekistan"), AlphaCode3("UZB")),
    VANUATU(Name("Vanuatu"), AlphaCode3("VUT")),
    VENEZUELA(Name("Venezuela (Bolivarian Republic of)"), AlphaCode3("VEN")),
    VIET_NAM(Name("Viet Nam"), AlphaCode3("VNM")),
    VIRGIN_ISLANDS_BRITISH(Name("Virgin Islands (British)"), AlphaCode3("VGB")),
    VIRGIN_ISLANDS_US(Name("Virgin Islands (U.S.)"), AlphaCode3("VIR")),
    WALLIS_AND_FUTUNA(Name("Wallis and Futuna"), AlphaCode3("WLF")),
    WESTERN_SAHARA(Name("Western Sahara"), AlphaCode3("ESH")),
    YEMEN(Name("Yemen"), AlphaCode3("YEM")),
    ZAMBIA(Name("Zambia"), AlphaCode3("ZMB")),
    ZIMBABWE(Name("Zimbabwe"), AlphaCode3("ZWE")),
    ;

    companion object {
        fun findByCode(code: AlphaCode3): Country? {
            return entries.find { it.alphaCode3.value == code.value }
        }
    }

    @JvmInline
    value class AlphaCode3(val value: String) {
        init {
            require(value.length == 3) { "Alpha code 3 must be exactly 3 characters long" }
        }
    }
}